Algoritmo "Exercicio02"

// Descrição: Ler o nome de um usuário e exibir uma mensagem de boas vindas
// Autor(a): Eduardo Felipe
// Data: 04/08/2026

Var
  nome :caractere


Inicio

  escreval("Informe seu nome: ")//Recebendo o nome do usuário
  leia(nome)

  escreval("Olá, ",nome,"! Seja muito Bem-Vindo! Você está participando do curso de Capacitação FullStack na Iteam!") // Dando as boas vindas com o nome do usuário conforme informado.


fimalgoritmo