Algoritmo "Exercicio05"

// Descrição: Ler um número e mostrar se é positivo ou negativo
// Autor(a): Eduardo Felipe
// Data: 04/08/2026

Var

numero : inteiro

Inicio
	escreval("Informe um número descobrir se é positivo ou negativo: ")
	leia(numero)
  
  se (numero >= 0) entao //Verificando se o número informado é maior ou Igual a 0
  	escreval("Número Positivo!")
  senao
  	escreval("Numero Negativo!")
  fimse



fimalgoritmo