Algoritmo "Exercicio3"


// Descrição: Média Aritmética: Crie um algoritmo que leia duas notas e calcule a média aritmética
// Autor(a): Eduardo Felipe Batista dos Reis
// Data: 03/08/2026

Var
  nota1, nota2 : inteiro
  media: real


Inicio
  escreval("Informe a primeira nota: ")
  leia(nota1)
  escreval("Informa a segunda nota: ")
  leia(nota2)

  media <- (nota1 + nota2)/2
	
  escreval("A média aritimética das notas ", nota1," e ", nota2, " é = ", media)



fimalgoritmo