Algoritmo "Exercio1"

// Descrição: Dobro e Triplo de um Número:
//						Crie um algoritmo que leia um número inteiro e exiba o seu dobro e o seu triplo
// Autor(a): Eduardo Felipe Batista dos Reis
// Data: 03/08/2026

Var
numero, dobro, triplo: inteiro



Inicio
    escreval("Informe um número: ")
    leia(numero)
    dobro <- numero * 2
    triplo <- numero * 3
    escreval("O dobro de ", numero, " é ", dobro, " e o triplo é ", triplo, "!")



fimalgoritmo