Algoritmo "Exercicio2"

// Descrição: Antecessor e Sucessor :
//						Crie um algoritmo que leia um número inteiro e mostre seu antecessor e sucessor
// Autor(a): Nome do(a) aluno(a)
// Data: 03/08/2026

Var
  numero, ant, suc: inteiro

Inicio
  escreval("Informe um número: ")
  leia(numero)

  ant <- numero -1
  suc <- numero + 1
	
  escreval("O Antecessor de ", numero, " é ", ant, " e o Sucessor é ", suc,"!")




fimalgoritmo