Algoritmo "Exercicio5"

// Descrição: Salário Mensal: 
//						Calcule o salário mensal de um funcionário que recebe por hora trabalhada
// Autor(a): Eduardo Felipe
// Data: 03/08/2026

Var
salarioMensal, horaTrabalhada, valorHora: real


Inicio
	escreval("Informe o valor da sua Hora Trabalhada: ")
	leia(valorHora)
  escreval("Informe Quantas horas você trabalhou esse mês: ")
  leia(horaTrabalhada)
  
  salarioMensal <- valorHora * horaTrabalhada
  escreval("Seu salário esse mês será de R$ ", salarioMensal)




fimalgoritmo