Algoritmo "Exercicio4"


// Descrição: Área do Triângulo: Crie um algoritmo que calcule a área de um triângulo.
// 															  Fórmula: área = (base x altura) /2
// Autor(a): Eduardo Felipe Batista dos Reis
// Data: 03/08/2026

Var
  area, base, altura : real


Inicio
  escreval("Informe a base: ")
  leia(base)
  escreval("Informe a altura: ")
  leia(altura)

  area <- (base * altura)/2
	
  escreval("A área do triângulo é ", area)


fimalgoritmo