Algoritmo "Exercicio18"

{Solicite a senha do usuário. Enquanto a senha estiver incorreta, informe "Senha incorreta!
 Tente novamente.". Quando acertar, informe "Acesso permitido.".}
// Autor(a): Eduardo Felipe
// Data: 09/08/2026

Var

senha : caractere

Inicio
    escreval("Informe sua senha: ")
    leia(senha)
    enquanto senha <> "5965" faca
        escreval("Senha Incorreta! Tente Novamente.")
        escreval("Informe sua senha: ")
        leia(senha)
    fimenquanto

    escreval("Acesso Permitido!")

    


fimalgoritmo